### ISSUE TITLE
[BUG] Not Found error when rendering the shinylive app

### ISSUE THREAD

**Issue by jarodmeng** [coatless-quarto/r-shinylive-demo#8]
I went to the site "https://quarto.thecoatlessprofessor.com/r-shinylive-demo/", but saw a "Not Found" error in the shinylive app (see screenshot attached). When I tried to render the preview locally by following the steps in the demo, I also had a "Not Found" error on local host.

<img width="1114" alt="Screenshot 2024-02-18 at 23 55 03" src="https://github.com/coatless-quarto/r-shinylive-demo/assets/854353/8c921d33-f86c-4482-9149-032a8884a39d">

**Comment by coatless** [comment]
@jarodmeng thanks for the report. 

The demo uses `{bslib}` package to create a collapsable sidebar instead of the included shiny layouts. The error happens because the `{bslib}` package is trying to re-create an existing directory. I've filed an issue upstream at: https://github.com/posit-dev/r-shinylive/issues/56

Details: 

<img width="918" alt="Screenshot 2024-02-18 at 10 08 51 AM" src="https://github.com/coatless-quarto/r-shinylive-demo/assets/833642/68d32858-0391-424b-8559-0440fe60854d">

**Comment by coatless** [comment]
@jarodmeng can you try now? This was just fixed by the `{shinylive}` team per 

https://github.com/posit-dev/r-shinylive/issues/56#issuecomment-1952547808

**Comment by jarodmeng** [comment]
It works now. Thanks.
